/*
 * Zotero Endpoint
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */



use crate::apis::ResponseContent;
use super::{Error, configuration};


/// struct for typed errors of method [`collection_add_to_current`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CollectionAddToCurrentError {
    UnknownValue(serde_json::Value),
}


/// Use citation keys or Zotero URIs to add items to the current selected collection.
pub async fn collection_add_to_current(configuration: &configuration::Configuration, cite_key: Option<&str>, uris: Option<&str>) -> Result<crate::models::EndpointResponse, Error<CollectionAddToCurrentError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/collection/addToCurrent", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = cite_key {
        local_var_req_builder = local_var_req_builder.query(&[("citeKey", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = uris {
        local_var_req_builder = local_var_req_builder.query(&[("uris", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<CollectionAddToCurrentError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

