/*
 * Zotero Endpoint
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EndpointResponseWithStringArray : Standard response body with a string array payload



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndpointResponseWithStringArray {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "payload")]
    pub payload: Vec<String>,
    #[serde(rename = "code")]
    pub code: i32,
}

impl EndpointResponseWithStringArray {
    /// Standard response body with a string array payload
    pub fn new(message: String, payload: Vec<String>, code: i32) -> EndpointResponseWithStringArray {
        EndpointResponseWithStringArray {
            message,
            payload,
            code,
        }
    }
}


