/*
 * Zotero Endpoint
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EndpointResponse : Standard response body



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EndpointResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "payload")]
    pub payload: serde_json::Value,
    #[serde(rename = "code")]
    pub code: i32,
}

impl EndpointResponse {
    /// Standard response body
    pub fn new(message: String, payload: serde_json::Value, code: i32) -> EndpointResponse {
        EndpointResponse {
            message,
            payload,
            code,
        }
    }
}


