/*
 * Zotero Endpoint
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SearchCondition : A search condition object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SearchCondition {
    #[serde(rename = "field")]
    pub field: Field,
    #[serde(rename = "operator")]
    pub operator: Operator,
    #[serde(rename = "query")]
    pub query: String,
}

impl SearchCondition {
    /// A search condition object
    pub fn new(field: Field, operator: Operator, query: String) -> SearchCondition {
        SearchCondition {
            field,
            operator,
            query,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Field {
    #[serde(rename = "citationKey")]
    CitationKey,
}

impl Default for Field {
    fn default() -> Field {
        Self::CitationKey
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "is")]
    Is,
    #[serde(rename = "contains")]
    Contains,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::Is
    }
}

